using Microsoft.Azure.Functions.Worker.Middleware;
using AzureFunctions.AzureEventGrid.Domain.Common.Exceptions;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using System.Threading.Tasks;
using System;
using System.Net;
using System.Text.Json;
using System.ComponentModel.DataAnnotations;

[assembly: DefaultIntentManaged(Mode.Fully)]

namespace AzureFunctions.AzureEventGrid.Api
{
    public class GlobalExceptionMiddleware : IFunctionsWorkerMiddleware
    {
        public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
        {
            try
            {
                await next(context);
            }
            catch (ValidationException ve)
            {
                await WriteJsonError(context, HttpStatusCode.BadRequest, ve.ValidationResult?.ErrorMessage ?? ve.Message);
            }
            catch (NotFoundException nf)
            {
                await WriteJsonError(context, HttpStatusCode.NotFound, nf.Message);
            }
            catch (JsonException je)
            {
                await WriteJsonError(context, HttpStatusCode.BadRequest, je.Message);
            }
            catch (FormatException fe)
            {
                await WriteJsonError(context, HttpStatusCode.BadRequest, fe.Message);
            }
            catch (Exception ex)
            {
                await WriteJsonError(context, HttpStatusCode.InternalServerError, "Internal server error!!!!");
            }
        }

        private static async Task WriteJsonError(FunctionContext context, HttpStatusCode statusCode, string message)
        {
            var req = await context.GetHttpRequestDataAsync();

            if (req is null)
            {
                return ;
            }
            var response = req.CreateResponse(statusCode);
            var error = new { error = message };
            await response.WriteAsJsonAsync(error);
            context.GetInvocationResult().Value = response;
        }
    }
}